CREATE TABLE users (
  id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(50) UNIQUE NOT NULL
);
